// Generated by setup.html on 9/27/2026. Spotify makes you redo this every ~6 months.
window.AUX_CONFIG = {
  "partyName": "Ben's Aux",
  "clientId": "c0d482384ba34280adb969654e30a694",
  "clientSecret": "94f7fbb6a50e400491cbad6b6755ff44",
  "refreshToken": "AQBjNTqJHlQv04T9Q1bbG6t9a5pixb60AXYFB9_ZZSU6C7CzLzuhPbv9diZ9Ucy2jsJdFmPj4Gi3uOUtmwn6l5gRMimBkU--cWr8nmCIKIb0Z7vTXLlx4YbYQGFXyEB8ECI",
  "playlistId": "43I7dcnHHnQBf5WOn6I6GW",
  "accessCode": ""
};
